// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1001
package admin

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "fmt"

type DashboardStatsData struct {
	TiendasPublicadas  int
	LocalesDisponibles int
	ReservasPendientes int
	VisitasHoy         int
	VisitasSemana      int
	NuevosLeads        int
}

func Dashboard() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div><div style=\"display:flex;align-items:center;justify-content:space-between;margin-bottom:24px\"><div><h2 style=\"font-size:1.1rem;font-weight:800;margin-bottom:4px\">Resumen</h2><p style=\"font-size:.8rem;color:var(--text-muted)\">Indicadores en tiempo real</p></div><a href=\"/index.html\" target=\"_blank\" class=\"topbar-btn topbar-btn-outline\"><span class=\"material-symbols-outlined\" style=\"font-size:14px\">open_in_new</span> Ver sitio</a></div><div id=\"dashboard-stats\" hx-get=\"/admin/dashboard/stats\" hx-trigger=\"load\" hx-swap=\"innerHTML\"><div class=\"stats-grid\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		for i := 0; i < 6; i++ {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<div class=\"stat-card\" style=\"opacity:.4\"><div class=\"stat-card-icon\" style=\"background:var(--surface-3)\"></div><div class=\"stat-card-value\">—</div><div class=\"stat-card-label\">Cargando...</div></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "</div></div><div style=\"display:grid;grid-template-columns:repeat(auto-fill,minmax(200px,1fr));gap:16px;margin-top:24px\"><a href=\"/admin/tiendas\" class=\"card\" style=\"padding:20px;display:flex;align-items:center;gap:12px\"><span class=\"material-symbols-outlined\" style=\"font-size:22px;color:var(--red)\">storefront</span><div><p style=\"font-size:.84rem;font-weight:700\">Tiendas</p><p style=\"font-size:.74rem;color:var(--text-muted)\">Gestionar directorio</p></div></a> <a href=\"/admin/locales\" class=\"card\" style=\"padding:20px;display:flex;align-items:center;gap:12px\"><span class=\"material-symbols-outlined\" style=\"font-size:22px;color:var(--blue)\">real_estate_agent</span><div><p style=\"font-size:.84rem;font-weight:700\">Locales</p><p style=\"font-size:.74rem;color:var(--text-muted)\">Disponibles en arriendo</p></div></a> <a href=\"/admin/content?cat=PROMOCION\" class=\"card\" style=\"padding:20px;display:flex;align-items:center;gap:12px\"><span class=\"material-symbols-outlined\" style=\"font-size:22px;color:var(--lime)\">celebration</span><div><p style=\"font-size:.84rem;font-weight:700\">Promociones</p><p style=\"font-size:.74rem;color:var(--text-muted)\">Eventos y ofertas</p></div></a> <a href=\"/admin/reservas\" class=\"card\" style=\"padding:20px;display:flex;align-items:center;gap:12px\"><span class=\"material-symbols-outlined\" style=\"font-size:22px;color:var(--text-mid)\">event_seat</span><div><p style=\"font-size:.84rem;font-weight:700\">Reservas</p><p style=\"font-size:.74rem;color:var(--text-muted)\">Ver pendientes</p></div></a></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func DashboardStats(d DashboardStatsData) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var2 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var2 == nil {
			templ_7745c5c3_Var2 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "<div class=\"stats-grid\"><div class=\"stat-card\"><div class=\"stat-card-icon\" style=\"background:rgba(215,16,85,.1)\"><span class=\"material-symbols-outlined\" style=\"color:var(--red)\">storefront</span></div><div class=\"stat-card-value\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var3 string
		templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(fmt.Sprintf("%d", d.TiendasPublicadas))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/view/pages/admin/dashboard.templ`, Line: 78, Col: 72}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "</div><div class=\"stat-card-label\">Tiendas publicadas</div></div><div class=\"stat-card\"><div class=\"stat-card-icon\" style=\"background:rgba(6,160,224,.1)\"><span class=\"material-symbols-outlined\" style=\"color:var(--blue)\">real_estate_agent</span></div><div class=\"stat-card-value\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var4 string
		templ_7745c5c3_Var4, templ_7745c5c3_Err = templ.JoinStringErrs(fmt.Sprintf("%d", d.LocalesDisponibles))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/view/pages/admin/dashboard.templ`, Line: 85, Col: 73}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var4))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "</div><div class=\"stat-card-label\">Locales disponibles</div></div><div class=\"stat-card\"><div class=\"stat-card-icon\" style=\"background:rgba(245,158,11,.1)\"><span class=\"material-symbols-outlined\" style=\"color:#f59e0b\">event_seat</span></div><div class=\"stat-card-value\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var5 string
		templ_7745c5c3_Var5, templ_7745c5c3_Err = templ.JoinStringErrs(fmt.Sprintf("%d", d.ReservasPendientes))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/view/pages/admin/dashboard.templ`, Line: 92, Col: 73}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var5))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 7, "</div><div class=\"stat-card-label\">Reservas pendientes</div></div><div class=\"stat-card\"><div class=\"stat-card-icon\" style=\"background:rgba(45,179,122,.1)\"><span class=\"material-symbols-outlined\" style=\"color:#2db37a\">visibility</span></div><div class=\"stat-card-value\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var6 string
		templ_7745c5c3_Var6, templ_7745c5c3_Err = templ.JoinStringErrs(fmt.Sprintf("%d", d.VisitasHoy))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/view/pages/admin/dashboard.templ`, Line: 99, Col: 65}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var6))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 8, "</div><div class=\"stat-card-label\">Visitas hoy</div></div><div class=\"stat-card\"><div class=\"stat-card-icon\" style=\"background:rgba(45,179,122,.07)\"><span class=\"material-symbols-outlined\" style=\"color:#2db37a\">bar_chart</span></div><div class=\"stat-card-value\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var7 string
		templ_7745c5c3_Var7, templ_7745c5c3_Err = templ.JoinStringErrs(fmt.Sprintf("%d", d.VisitasSemana))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/view/pages/admin/dashboard.templ`, Line: 106, Col: 68}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var7))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 9, "</div><div class=\"stat-card-label\">Visitas esta semana</div></div><div class=\"stat-card\"><div class=\"stat-card-icon\" style=\"background:rgba(172,198,13,.1)\"><span class=\"material-symbols-outlined\" style=\"color:var(--lime)\">group_add</span></div><div class=\"stat-card-value\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var8 string
		templ_7745c5c3_Var8, templ_7745c5c3_Err = templ.JoinStringErrs(fmt.Sprintf("%d", d.NuevosLeads))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/view/pages/admin/dashboard.templ`, Line: 113, Col: 66}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var8))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 10, "</div><div class=\"stat-card-label\">Nuevos leads (7 días)</div></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
